services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: chip_enterprise
      POSTGRES_DB: chip
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

volumes:
  pgdata:
